In [2]:
import pandas as pd

In [1]:
import pandas as pd
with open('datasets/dataset.txt','r',encoding='utf-8') as file:
    text_list = file.readlines()
    data = pd.DataFrame(text_list)
data

                                                        0
0                  __label__INSULT скотина! что сказать\n
1       __label__NORMAL я сегодня проезжала по рабочей...
2       __label__NORMAL очередной лохотрон. зачем прид...
3       __label__NORMAL ретро дежавю ... сложно понять...
4       __label__NORMAL а когда мы статус агрогородка ...
...                                                   ...
248285     __label__NORMAL правильно всё по пять (5)...\n
248286  __label__INSULT ёбанные нубы заходите на серве...
248287  __label__NORMAL а у меня наверное рекорд в 196...
248288            __label__NORMAL спасибо всем большое)\n
248289  __label__NORMAL нельзя ли увеличить хотя бы в ...

[248290 rows x 1 columns]

In [2]:
def label_split(text):
    separator = text.find(' ')
    label = text[:separator]
    comment = text[separator+1:]
    return label, comment
data = data[0].apply(label_split)

In [3]:
df = pd.DataFrame(data = list(data),columns=['label','comment'])
df

                  label                                            comment
0       __label__INSULT                             скотина! что сказать\n
1       __label__NORMAL  я сегодня проезжала по рабочей и между домами ...
2       __label__NORMAL  очередной лохотрон. зачем придумывать очередно...
3       __label__NORMAL  ретро дежавю ... сложно понять чужое сердце , ...
4       __label__NORMAL          а когда мы статус агрогородка получили?\n
...                 ...                                                ...
248285  __label__NORMAL                     правильно всё по пять (5)...\n
248286  __label__INSULT  ёбанные нубы заходите на сервер мой ник _creep...
248287  __label__NORMAL  а у меня наверное рекорд в 1962 году в училище...
248288  __label__NORMAL                            спасибо всем большое)\n
248289  __label__NORMAL  нельзя ли увеличить хотя бы в два раза некотор...

[248290 rows x 2 columns]

In [4]:
df.loc[df['label'] == '__label__NORMAL','label'] = 'normal'
df.loc[df['label'] != 'normal','label'] = 'toxic'
df

         label                                            comment
0        toxic                             скотина! что сказать\n
1       normal  я сегодня проезжала по рабочей и между домами ...
2       normal  очередной лохотрон. зачем придумывать очередно...
3       normal  ретро дежавю ... сложно понять чужое сердце , ...
4       normal          а когда мы статус агрогородка получили?\n
...        ...                                                ...
248285  normal                     правильно всё по пять (5)...\n
248286   toxic  ёбанные нубы заходите на сервер мой ник _creep...
248287  normal  а у меня наверное рекорд в 1962 году в училище...
248288  normal                            спасибо всем большое)\n
248289  normal  нельзя ли увеличить хотя бы в два раза некотор...

[248290 rows x 2 columns]

In [5]:
df['label'].value_counts()

normal    203685
toxic      44605
Name: label, dtype: int64

In [6]:
data = pd.read_csv('datasets/cleaned_data_hatespeech.csv')
data

                                             comment_text  toxic lang
0       personnage ainsi q tte la clique gauchiste deg...      1   fr
1            bah oui t'as raison l'autre c'est un mongol.      1   fr
2       moi j'ai personne à qui m'adresser pour réclam...      1   fr
3       c...est vrai que les anchois sont aller sur la...      0   fr
4                      eh les renois faut se réveiller la      0   fr
...                                                   ...    ...  ...
117377  Crescere a Cupa Perillo, il campo rom dentro S...      0   it
117378  Prima mi manda l'ufficio immigrazione in alber...      0   it
117379  ... E che gli immigrati ci pagano la pensione ...      0   it
117380  Intervista choc a imam: “Roma è già musulmana....      0   it
117381  Gabrielli, ospite della Befana SAP, all'Ansa: ...      0   it

[117382 rows x 3 columns]

In [7]:
data = data[data['lang']=='ru']

In [8]:
data.loc[data['toxic']==1,'toxic'] = 'toxic'
data.loc[data['toxic']==0,'toxic'] = 'normal'

In [9]:
data['toxic'].value_counts()

normal    9586
toxic     4826
Name: toxic, dtype: int64

In [10]:
data

                                            comment_text   toxic lang
81393                 Верблюдов-то за что? Дебилы, бл...   toxic   ru
81394  Хохлы, это отдушина затюканого россиянина, мол...   toxic   ru
81395                            Собаке - собачья смерть   toxic   ru
81396  Страницу обнови, дебил. Это тоже не оскорблени...   toxic   ru
81397  тебя не убедил 6-страничный пдф в том, что Скр...   toxic   ru
...                                                  ...     ...  ...
95800  Вонючий совковый скот прибежал и ноет. А вот и...   toxic   ru
95801  А кого любить? Гоблина тупорылого что-ли? Или ...   toxic   ru
95802  Посмотрел Утомленных солнцем 2. И оказалось, ч...  normal   ru
95803  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...   toxic   ru
95804  До сих пор пересматриваю его видео. Орамбо кст...  normal   ru

[14412 rows x 3 columns]

In [11]:
data.drop(columns='lang',inplace=True)
data.columns = ['comment','label']

C:\Users\nicka\AppData\Local\Temp\ipykernel_7756\647073028.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns='lang',inplace=True)

In [12]:
df = pd.concat([df,data],axis=0)
df

        label                                            comment
0       toxic                             скотина! что сказать\n
1      normal  я сегодня проезжала по рабочей и между домами ...
2      normal  очередной лохотрон. зачем придумывать очередно...
3      normal  ретро дежавю ... сложно понять чужое сердце , ...
4      normal          а когда мы статус агрогородка получили?\n
...       ...                                                ...
95800   toxic  Вонючий совковый скот прибежал и ноет. А вот и...
95801   toxic  А кого любить? Гоблина тупорылого что-ли? Или ...
95802  normal  Посмотрел Утомленных солнцем 2. И оказалось, ч...
95803   toxic  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...
95804  normal  До сих пор пересматриваю его видео. Орамбо кст...

[262702 rows x 2 columns]

In [13]:
data = pd.read_csv('datasets/labeled.csv')
data

                                                 comment  toxic
0                   Верблюдов-то за что? Дебилы, бл...\n    1.0
1      Хохлы, это отдушина затюканого россиянина, мол...    1.0
2                              Собаке - собачья смерть\n    1.0
3      Страницу обнови, дебил. Это тоже не оскорблени...    1.0
4      тебя не убедил 6-страничный пдф в том, что Скр...    1.0
...                                                  ...    ...
14407  Вонючий совковый скот прибежал и ноет. А вот и...    1.0
14408  А кого любить? Гоблина тупорылого что-ли? Или ...    1.0
14409  Посмотрел Утомленных солнцем 2. И оказалось, ч...    0.0
14410  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...    1.0
14411  До сих пор пересматриваю его видео. Орамбо кст...    0.0

[14412 rows x 2 columns]

In [14]:
data.loc[data['toxic']==1,'toxic'] = 'toxic'
data.loc[data['toxic']==0,'toxic'] = 'normal'
data.toxic.value_counts()

normal    9586
toxic     4826
Name: toxic, dtype: int64

In [15]:
data

                                                 comment   toxic
0                   Верблюдов-то за что? Дебилы, бл...\n   toxic
1      Хохлы, это отдушина затюканого россиянина, мол...   toxic
2                              Собаке - собачья смерть\n   toxic
3      Страницу обнови, дебил. Это тоже не оскорблени...   toxic
4      тебя не убедил 6-страничный пдф в том, что Скр...   toxic
...                                                  ...     ...
14407  Вонючий совковый скот прибежал и ноет. А вот и...   toxic
14408  А кого любить? Гоблина тупорылого что-ли? Или ...   toxic
14409  Посмотрел Утомленных солнцем 2. И оказалось, ч...  normal
14410  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...   toxic
14411  До сих пор пересматриваю его видео. Орамбо кст...  normal

[14412 rows x 2 columns]

In [16]:
data.columns = ['comment','label']
data

                                                 comment   label
0                   Верблюдов-то за что? Дебилы, бл...\n   toxic
1      Хохлы, это отдушина затюканого россиянина, мол...   toxic
2                              Собаке - собачья смерть\n   toxic
3      Страницу обнови, дебил. Это тоже не оскорблени...   toxic
4      тебя не убедил 6-страничный пдф в том, что Скр...   toxic
...                                                  ...     ...
14407  Вонючий совковый скот прибежал и ноет. А вот и...   toxic
14408  А кого любить? Гоблина тупорылого что-ли? Или ...   toxic
14409  Посмотрел Утомленных солнцем 2. И оказалось, ч...  normal
14410  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...   toxic
14411  До сих пор пересматриваю его видео. Орамбо кст...  normal

[14412 rows x 2 columns]

In [17]:
df = pd.concat([df,data],axis=0)
df

        label                                            comment
0       toxic                             скотина! что сказать\n
1      normal  я сегодня проезжала по рабочей и между домами ...
2      normal  очередной лохотрон. зачем придумывать очередно...
3      normal  ретро дежавю ... сложно понять чужое сердце , ...
4      normal          а когда мы статус агрогородка получили?\n
...       ...                                                ...
14407   toxic  Вонючий совковый скот прибежал и ноет. А вот и...
14408   toxic  А кого любить? Гоблина тупорылого что-ли? Или ...
14409  normal  Посмотрел Утомленных солнцем 2. И оказалось, ч...
14410   toxic  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...
14411  normal  До сих пор пересматриваю его видео. Орамбо кст...

[277114 rows x 2 columns]

In [18]:
data = pd.read_csv('datasets/labeled_1.csv')
data

                                                 comment  toxic
0                   Верблюдов-то за что? Дебилы, бл...\n    1.0
1      Хохлы, это отдушина затюканого россиянина, мол...    1.0
2                              Собаке - собачья смерть\n    1.0
3      Страницу обнови, дебил. Это тоже не оскорблени...    1.0
4      тебя не убедил 6-страничный пдф в том, что Скр...    1.0
...                                                  ...    ...
14407  Вонючий совковый скот прибежал и ноет. А вот и...    1.0
14408  А кого любить? Гоблина тупорылого что-ли? Или ...    1.0
14409  Посмотрел Утомленных солнцем 2. И оказалось, ч...    0.0
14410  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...    1.0
14411  До сих пор пересматриваю его видео. Орамбо кст...    0.0

[14412 rows x 2 columns]

In [19]:
data.loc[data['toxic']==1,'toxic'] = 'toxic'
data.loc[data['toxic']==0,'toxic'] = 'normal'
print(data.toxic.value_counts())
data.columns = ['comment','label']
data

normal    9586
toxic     4826
Name: toxic, dtype: int64

                                                 comment   label
0                   Верблюдов-то за что? Дебилы, бл...\n   toxic
1      Хохлы, это отдушина затюканого россиянина, мол...   toxic
2                              Собаке - собачья смерть\n   toxic
3      Страницу обнови, дебил. Это тоже не оскорблени...   toxic
4      тебя не убедил 6-страничный пдф в том, что Скр...   toxic
...                                                  ...     ...
14407  Вонючий совковый скот прибежал и ноет. А вот и...   toxic
14408  А кого любить? Гоблина тупорылого что-ли? Или ...   toxic
14409  Посмотрел Утомленных солнцем 2. И оказалось, ч...  normal
14410  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...   toxic
14411  До сих пор пересматриваю его видео. Орамбо кст...  normal

[14412 rows x 2 columns]

In [20]:
df = pd.concat([df,data],axis=0)
df

        label                                            comment
0       toxic                             скотина! что сказать\n
1      normal  я сегодня проезжала по рабочей и между домами ...
2      normal  очередной лохотрон. зачем придумывать очередно...
3      normal  ретро дежавю ... сложно понять чужое сердце , ...
4      normal          а когда мы статус агрогородка получили?\n
...       ...                                                ...
14407   toxic  Вонючий совковый скот прибежал и ноет. А вот и...
14408   toxic  А кого любить? Гоблина тупорылого что-ли? Или ...
14409  normal  Посмотрел Утомленных солнцем 2. И оказалось, ч...
14410   toxic  КРЫМОТРЕД НАРУШАЕТ ПРАВИЛА РАЗДЕЛА Т.К В НЕМ Н...
14411  normal  До сих пор пересматриваю его видео. Орамбо кст...

[291526 rows x 2 columns]

In [21]:
data = pd.read_csv('datasets/positive.csv')
data

,id,tdate,tname,ttext,ttype,trep,trtw,tfav,tstcount,tfoll,tfrien,listcount
0,408906692374446080,1386325927,pleease_shut_up,"@first_timee хоть я и школота, но поверь, у на...",1,0,0,0,7569,62,61,0
1,408906692693221377,1386325927,alinakirpicheva,"Да, все-таки он немного похож на него. Но мой ...",1,0,0,0,11825,59,31,2
2,408906695083954177,1386325927,EvgeshaRe,RT @KatiaCheh: Ну ты идиотка) я испугалась за ...,1,0,1,0,1273,26,27,0
3,408906695356973056,1386325927,ikonnikova_21,"RT @digger2912: ""Кто то в углу сидит и погибае...",1,0,1,0,1549,19,17,0
4,408906761416867842,1386325943,JumpyAlex,@irina_dyshkant Вот что значит страшилка :D\nН...,1,0,0,0,597,16,23,1
...,...,...,...,...,...,...,...,...,...,...,...,...
114906,411368729235054592,1386912922,diminlisenok,"Спала в родительском доме, на своей кровати......",1,0,0,0,1497,56,34,2
114907,411368729424187392,1386912922,qilepocagotu,RT @jebesilofyt: Эх... Мы немного решили сокра...,1,0,1,0,692,225,210,0
114908,411368796537257984,1386912938,DennyChooo,"Что происходит со мной, когда в эфире #proacti...",1,0,0,0,4905,448,193,13
114909,411368797447417856,1386912938,bedowabymir,"""Любимая,я подарю тебе эту звезду..."" Имя како...",1,0,0,0,989,254,251,0
114910,411368857035898880,1386912953,Prituljak_Sibir,@Ma_che_rie посмотри #непытайтесьпокинутьомск ...,1,0,0,0,1005,221,178,6

In [22]:
data.drop(columns=['id','tdate','tname','trep','trtw','tfav','tstcount','tfoll','tfrien','listcount'],inplace=True)
data

                                                    ttext  ttype
0       @first_timee хоть я и школота, но поверь, у на...      1
1       Да, все-таки он немного похож на него. Но мой ...      1
2       RT @KatiaCheh: Ну ты идиотка) я испугалась за ...      1
3       RT @digger2912: "Кто то в углу сидит и погибае...      1
4       @irina_dyshkant Вот что значит страшилка :D\nН...      1
...                                                   ...    ...
114906  Спала в родительском доме, на своей кровати......      1
114907  RT @jebesilofyt: Эх... Мы немного решили сокра...      1
114908  Что происходит со мной, когда в эфире #proacti...      1
114909  "Любимая,я подарю тебе эту звезду..." Имя како...      1
114910  @Ma_che_rie посмотри #непытайтесьпокинутьомск ...      1

[114911 rows x 2 columns]

In [23]:
data.columns = ['comment','label']
data.loc[data['label'] == 1,'label'] = 'normal'
data

                                                  comment   label
0       @first_timee хоть я и школота, но поверь, у на...  normal
1       Да, все-таки он немного похож на него. Но мой ...  normal
2       RT @KatiaCheh: Ну ты идиотка) я испугалась за ...  normal
3       RT @digger2912: "Кто то в углу сидит и погибае...  normal
4       @irina_dyshkant Вот что значит страшилка :D\nН...  normal
...                                                   ...     ...
114906  Спала в родительском доме, на своей кровати......  normal
114907  RT @jebesilofyt: Эх... Мы немного решили сокра...  normal
114908  Что происходит со мной, когда в эфире #proacti...  normal
114909  "Любимая,я подарю тебе эту звезду..." Имя како...  normal
114910  @Ma_che_rie посмотри #непытайтесьпокинутьомск ...  normal

[114911 rows x 2 columns]

In [24]:
df = pd.concat([df,data],axis=0)
df

         label                                            comment
0        toxic                             скотина! что сказать\n
1       normal  я сегодня проезжала по рабочей и между домами ...
2       normal  очередной лохотрон. зачем придумывать очередно...
3       normal  ретро дежавю ... сложно понять чужое сердце , ...
4       normal          а когда мы статус агрогородка получили?\n
...        ...                                                ...
114906  normal  Спала в родительском доме, на своей кровати......
114907  normal  RT @jebesilofyt: Эх... Мы немного решили сокра...
114908  normal  Что происходит со мной, когда в эфире #proacti...
114909  normal  "Любимая,я подарю тебе эту звезду..." Имя како...
114910  normal  @Ma_che_rie посмотри #непытайтесьпокинутьомск ...

[406437 rows x 2 columns]

In [25]:
df.label.value_counts()

normal    347354
toxic      59083
Name: label, dtype: int64

In [26]:
df

         label                                            comment
0        toxic                             скотина! что сказать\n
1       normal  я сегодня проезжала по рабочей и между домами ...
2       normal  очередной лохотрон. зачем придумывать очередно...
3       normal  ретро дежавю ... сложно понять чужое сердце , ...
4       normal          а когда мы статус агрогородка получили?\n
...        ...                                                ...
114906  normal  Спала в родительском доме, на своей кровати......
114907  normal  RT @jebesilofyt: Эх... Мы немного решили сокра...
114908  normal  Что происходит со мной, когда в эфире #proacti...
114909  normal  "Любимая,я подарю тебе эту звезду..." Имя како...
114910  normal  @Ma_che_rie посмотри #непытайтесьпокинутьомск ...

[406437 rows x 2 columns]

In [56]:
df_cop = df.copy()
df_cop

         label                                            comment
0        toxic                             скотина! что сказать\n
1       normal  я сегодня проезжала по рабочей и между домами ...
2       normal  очередной лохотрон. зачем придумывать очередно...
3       normal  ретро дежавю ... сложно понять чужое сердце , ...
4       normal          а когда мы статус агрогородка получили?\n
...        ...                                                ...
114906  normal  Спала в родительском доме, на своей кровати......
114907  normal  RT @jebesilofyt: Эх... Мы немного решили сокра...
114908  normal  Что происходит со мной, когда в эфире #proacti...
114909  normal  "Любимая,я подарю тебе эту звезду..." Имя како...
114910  normal  @Ma_che_rie посмотри #непытайтесьпокинутьомск ...

[406437 rows x 2 columns]

In [57]:
df_cop.isna().sum()

label      0
comment    0
dtype: int64

In [58]:
df_cop.drop_duplicates(inplace=True)
df_cop.reset_index(drop=True,inplace=True)
df_cop

         label                                            comment
0        toxic                             скотина! что сказать\n
1       normal  я сегодня проезжала по рабочей и между домами ...
2       normal  очередной лохотрон. зачем придумывать очередно...
3       normal  ретро дежавю ... сложно понять чужое сердце , ...
4       normal          а когда мы статус агрогородка получили?\n
...        ...                                                ...
386325  normal  Спала в родительском доме, на своей кровати......
386326  normal  RT @jebesilofyt: Эх... Мы немного решили сокра...
386327  normal  Что происходит со мной, когда в эфире #proacti...
386328  normal  "Любимая,я подарю тебе эту звезду..." Имя како...
386329  normal  @Ma_che_rie посмотри #непытайтесьпокинутьомск ...

[386330 rows x 2 columns]

In [59]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
from pymorphy3 import MorphAnalyzer
import re
patterns = "[A-Za-z0-9!#$%&'()*+,./:;<=>?@[\]^_`{|}~—\"\-]+"
stopwords_ru = stopwords.words("russian")
morph = MorphAnalyzer()
stemmer = PorterStemmer()
def lemmatize(text):
    doc = re.sub(patterns, ' ', text)
    tokens = word_tokenize(doc, language='russian')
    lemmas = [morph.parse(token)[0].normal_form for token in tokens if token.lower() not in stopwords_ru]
    stems = [stemmer.stem(token) for token in tokens]
    return stems


df_cop['comment'] = df_cop['comment'].apply(lemmatize)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nicka\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nicka\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [64]:
def concat(text):
    text= ' '.join(text)
    return text

df_cop['comment'] = df_cop['comment'].apply(concat)

In [60]:
df_cop['comment']

0                                   [скотина, что, сказать]
1         [я, сегодня, проезжала, по, рабочей, и, между,...
2         [очередной, лохотрон, зачем, придумывать, очер...
3         [ретро, дежавю, сложно, понять, чужое, сердце,...
4             [а, когда, мы, статус, агрогородка, получили]
                                ...
386325    [спала, в, родительском, доме, на, своей, кров...
386326    [эх, мы, немного, решили, сократить, путь, сей...
386327    [что, происходит, со, мной, когда, в, эфире, з...
386328    [любимая, я, подарю, тебе, эту, звезду, имя, к...
386329    [посмотри, непытайтесьпокинутьомск, сегодня, в...
Name: comment, Length: 386330, dtype: object

In [61]:
#df_cop.to_csv('tokenized_data.csv')

In [1]:
import pandas as pd
df_cop = pd.read_csv('tokenized_data.csv')

In [2]:
df_cop

        Unnamed: 0   label                                            comment
0                0   toxic                      ['скотина', 'что', 'сказать']
1                1  normal  ['я', 'сегодня', 'проезжала', 'по', 'рабочей',...
2                2  normal  ['очередной', 'лохотрон', 'зачем', 'придумыват...
3                3  normal  ['ретро', 'дежавю', 'сложно', 'понять', 'чужое...
4                4  normal  ['а', 'когда', 'мы', 'статус', 'агрогородка', ...
...            ...     ...                                                ...
386325      386325  normal  ['спала', 'в', 'родительском', 'доме', 'на', '...
386326      386326  normal  ['эх', 'мы', 'немного', 'решили', 'сократить',...
386327      386327  normal  ['что', 'происходит', 'со', 'мной', 'когда', '...
386328      386328  normal  ['любимая', 'я', 'подарю', 'тебе', 'эту', 'зве...
386329      386329  normal  ['посмотри', 'непытайтесьпокинутьомск', 'сегод...

[386330 rows x 3 columns]

In [3]:
df_cop.drop(columns='Unnamed: 0',inplace=True)
df_cop

         label                                            comment
0        toxic                      ['скотина', 'что', 'сказать']
1       normal  ['я', 'сегодня', 'проезжала', 'по', 'рабочей',...
2       normal  ['очередной', 'лохотрон', 'зачем', 'придумыват...
3       normal  ['ретро', 'дежавю', 'сложно', 'понять', 'чужое...
4       normal  ['а', 'когда', 'мы', 'статус', 'агрогородка', ...
...        ...                                                ...
386325  normal  ['спала', 'в', 'родительском', 'доме', 'на', '...
386326  normal  ['эх', 'мы', 'немного', 'решили', 'сократить',...
386327  normal  ['что', 'происходит', 'со', 'мной', 'когда', '...
386328  normal  ['любимая', 'я', 'подарю', 'тебе', 'эту', 'зве...
386329  normal  ['посмотри', 'непытайтесьпокинутьомск', 'сегод...

[386330 rows x 2 columns]

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_counts = count_vect.fit_transform(df_cop['comment'])
X_counts.shape

(386330, 310760)

In [5]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer().fit(X_counts)
X_tfidf = tf_transformer.transform(X_counts)
X_tfidf.shape

(386330, 310760)

In [6]:
from sklearn.decomposition import TruncatedSVD
clf = TruncatedSVD(30)
X_decom = clf.fit_transform(X_tfidf)
X_decom

array([[ 0.09023797, -0.00088151,  0.06396835, ..., -0.00583157,
         0.00239906,  0.00030532],
       [ 0.04433087, -0.00904804,  0.01572243, ..., -0.00480527,
        -0.00182304,  0.00894138],
       [ 0.11764319, -0.03989457,  0.00994863, ...,  0.02546205,
        -0.00745451, -0.01789728],
       ...,
       [ 0.07141428,  0.00328241,  0.04408782, ...,  0.00132588,
         0.00426098,  0.02853476],
       [ 0.02023145,  0.0010683 ,  0.02380119, ...,  0.03518523,
        -0.03562243,  0.0102628 ],
       [ 0.05064794, -0.00645217,  0.03695514, ...,  0.08215535,
         0.11421693,  0.03444499]])

In [7]:
X = X_decom.copy()
y = df_cop['label']

In [13]:
X = X_tfidf.copy()
y = df_cop['label']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
from imblearn.under_sampling import RandomUnderSampler
undersampler = RandomUnderSampler()
X_train, y_train = undersampler.fit_resample(X_train, y_train)

In [10]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report

# Получение весов классов
#class_weights = compute_class_weight('balanced', classes=np.unique(y), y=y)

# Создание модели с взвешиванием классов
model = RandomForestClassifier()
model.fit(X_train,y_train)
print(classification_report(y_test,model.predict(X_test)))

NameError: name 'classification_report' is not defined

In [13]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state=42)

X_train, y_train = sm.fit_resample(X_train, y_train)

In [28]:
from imblearn.over_sampling import ADASYN
adasyn = ADASYN()

X_train, y_train = adasyn.fit_resample(X_train, y_train)

# Truncated

In [37]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.metrics import classification_report

clf2 = GaussianNB()
clf3 = BernoulliNB()

clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)
print(classification_report(y_test,clf2.predict(X_test)),classification_report(y_test,clf3.predict(X_test)),sep = '\n')

              precision    recall  f1-score   support

      normal       0.90      0.50      0.65    109687
       toxic       0.18      0.67      0.28     17802

    accuracy                           0.53    127489
   macro avg       0.54      0.59      0.47    127489
weighted avg       0.80      0.53      0.60    127489

              precision    recall  f1-score   support

      normal       0.87      0.99      0.93    109687
       toxic       0.64      0.07      0.13     17802

    accuracy                           0.86    127489
   macro avg       0.75      0.53      0.53    127489
weighted avg       0.84      0.86      0.82    127489

# Sparced

In [15]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report
model = SGDClassifier(loss='hinge')
model.fit(X_train,y_train)

SGDClassifier()

In [16]:
print(classification_report(y_test,model.predict(X_test)))

              precision    recall  f1-score   support

      normal       0.90      1.00      0.95    109687
       toxic       0.97      0.31      0.47     17802

    accuracy                           0.90    127489
   macro avg       0.93      0.66      0.71    127489
weighted avg       0.91      0.90      0.88    127489